### PR TITLE
updates for SLP 3.4.7

### PR DESCRIPTION
**Pull request by jcramer**

### CODE REVIEW

**Comment by cculianu** [comment]
James -- hey man you added the binaries, mac .dmg, linux .AppImage. You perhaps did this either by 
mistake, or because you weren't clear on what this repo is for.

This repo is for hosting *only* signatures and sha256sums, not the binaries themselves.  Those go on electroncash.org's web server (and possibly github release pages).

The repo is now 244+ MB because of this.

Please avoid doing this in the future! Now, when someone clones it locally they will curse us under their breath and also think we're idiots for having such a bloated repo.. :/

**Comment by jcramer** [comment]
Ah crap. Sorry about that.  You can always create a fresh repo... 

I did some research on using `git gc` but it doesn't look like that can be applied to remote repos?

**Comment by jcramer** [comment]
@cculianu probably what we could do is reset the repo to the commit before this happened and then one of us should apply the recent changes and `git push -f`

**Comment by cculianu** [comment]
I am not sure that will kill the binary blobs.  I think you have to do evil hax to get rid of the binaries.. I remember having to do it once for a repo and it was bizarre.  I'll look into it.

**Comment by cculianu** [comment]
And yeah easiest thing would be to recreate the repo as a fresh repo...

**Comment by jcramer** [comment]
> And yeah easiest thing would be to recreate the repo as a fresh repo...

that's fine if you don't care about the history in this repo.  I verified on my remote fork this works and reduces the remote repo size to about 21mb:

1. reset local repo to the commit before I made that mistake `git reset 1df8606a8f20bff3fb3a53d54f1e0da0cc044f4f`
2. then a bunch of changes from after that reset point will be added to "unstaged changes".  Stage the changes you want to keep (i.e., not the binary files)
3. make a clean commit on top of the reset point
4. `git push -f`

**Comment by cculianu** [comment]
21mb is still huge.  I suspect we didn't get all the binaries, lol.

But yeah that's the idea.  I don't think jonald cares about history...

**Comment by cculianu** [comment]
Note you're not the only 1 that did this.  I found some ancient binaries in there from other people that made the same mistake.  Before we do this all should be removed and repo should just be created from scratch.. my two cents.

**Comment by cculianu** [comment]
Yeah your reset point still has binaries in it.  I removed them since then.. repo should be 2MB tops at this point if we wipe the history and start from scratch.

Up to Jonald if he wants to do this.... @fyookball 

~200MB right now is huge to synch and *does* make us look a little nubbish.. so.. I would recommend he does this if he gets bored at some point. Just start from scratch and `git add` all the top-level dirs and files from here...

**Pull request merged**
